add: share

diff --git a/.github/workflows/3-workflows.yml b/.github/workflows/3-workflows.yml
--- a/.github/workflows/3-workflows.yml
+++ b/.github/workflows/3-workflows.yml
@@ -1,5 +1,5 @@
 name: 3 Workflow
-run-name: Run by @${{ github.actor }} # ワークフロー実行名の指定
+#run-name: Run by @${{ github.actor }} # ワークフロー実行名の指定
 on: push
 jobs:
   print-actor:
@@ -24,18 +24,18 @@ jobs:
       - run: echo "${PASSWORD}"
       - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
 
-  fail-with-failure:
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1             # error発生
-      - run: echo "hello"
-        if : ${{ failure() }}   # エラー発生するがfailure関数により実行される
-
-  fail-with-out-failure:
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1             # error発生
-      - run: echo "hello"
+#  fail-with-failure:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - run: exit 1             # error発生
+#      - run: echo "hello"
+#        if : ${{ failure() }}   # エラー発生するがfailure関数により実行される
+#
+#  fail-with-out-failure:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - run: exit 1             # error発生
+#      - run: echo "hello"
 
   skip-or-run:
     if: ${{ github.actor == 'ak0327' }}  # 指定アカウントのみ実行
@@ -49,3 +49,13 @@ jobs:
     steps:
       - name: Steps Name
         run: echo "hello"
+
+  share-output:
+    name: Share Output
+    runs-on: ubuntu-latest
+    steps:
+      - id: source                                      # step idを設定
+        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"  # GITHUB_OUTPUTへ書き出し
+      - env:
+          RESULT: ${{ steps.source.outputs.result }}    # stepsコンテキストから参照
+        run: echo "${RESULT}"
